jobs:
  - job: plan_terraform
    displayName: "Run Plan"
    steps:
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'
      continueOnError: false
    - task: TerraformTaskV4@4
      displayName: 'Run Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'devtestserverconnection'
        backendAzureRmResourceGroupName: '$(bkstrgrg)'
        backendAzureRmStorageAccountName: '$(bkstrg)'
        backendAzureRmContainerName: '$(bkcontainer)'
        backendAzureRmKey: '$(bkstrgkey)'
      continueOnError: false
    - task: TerraformTaskV4@4
      displayName: 'Select Workspace'
      inputs:
        provider: 'azurerm'
        command: 'custom'
        customCommand: 'workspace'
        commandOptions: 'select $(env)'
        outputTo: 'console'
        environmentServiceNameAzureRM: 'devtestserverconnection'
    - task: TerraformTaskV4@4
      displayName: 'Run Terraform Plan'
      inputs:
         provider: 'azurerm'
         command: 'plan'
         #commandOptions: MISSING TFVARS
         environmentServiceNameAzureRM: 'devtestserverconnection'
         commandOptions: '- -out="terraform.tfplan"'
      continueOnError: false
