jobs:
  - job: prep_terraform
    displayName: "Setup terraform"


    steps:
      - task: TerraformInstaller@1
        displayName: 'Install Terraform'
        inputs:
          terraformVersion: 'latest'
        continueOnError: false

      - task: TerraformTaskV4@4
        displayName: 'Run Init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'devtestserverconnection'
          backendAzureRmResourceGroupName: '$(bkstrgrg)'
          backendAzureRmStorageAccountName: '$(bkstrg)'
          backendAzureRmContainerName: '$(bkcontainer)'
          backendAzureRmKey: '$(bkstrgkey)'
        continueOnError: false

      - task: TerraformTaskV4@4
        displayName: 'Run validate'
        inputs:
          provider: 'azurerm'
          command: 'validate'
        continueOnError: false
  