jobs:
  - job: deploy_terraform
    displayName: "Terraform Deploy"
    steps:
    - download: current # get latest artifact
      artifact: 'planfile' #fetch the output file from the plan phase
    
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'
      continueOnError: false
    - task: TerraformTaskV4@4
      displayName: 'Run Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'devtestserverconnection'
        backendAzureRmResourceGroupName: '$(bkstrgrg)'
        backendAzureRmStorageAccountName: '$(bkstrg)'
        backendAzureRmContainerName: '$(bkcontainer)'
        backendAzureRmKey: '$(bkstrgkey)'
    - task: TerraformTaskV4@4
      displayName: 'Select Workspace'
      inputs:
        provider: 'azurerm'
        command: 'custom'
        outputTo: 'console'
        customCommand: 'workspace'
        commandOptions: 'select $(env)'
        environmentServiceNameAzureRM: 'devtestserverconnection'
    - task: TerraformTaskV4@4
      displayName: 'Run apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        #commandOptions: MISSING TFVARS
        environmentServiceNameAzureRM: 'devtestserverconnection'
        workingDirectory: '$(Pipeline.Workspace)'
        commandOptions: '$(Pipeline.Workspace)/planfile/terraform-dev.tfplan'
      continueOnError: false

